classdef W_tools < W_tools_basic & ...
        W_tools_print & ...
        W_tools_tools & ...
        W_tools_cell & ...
        W_tools_string & ...
        W_tools_table & ...
        W_tools_struct & ...
        W_tools_JAGS
    properties
    end
    methods(Static)
    end
end