classdef W_neuro < W_neuro_ANOVA & ...
        W_neuro_PCA & ...
        W_neuro_EnergyLandscape & ...
        W_neuro_1D_dynamics & ...
        W_neuro_nD_dynamics & ...
        W_neuro_spikes_cleaning
    properties
    end
    methods(Static)
    end
end